[project]
name = "password-strength-meter"
version = "0.1.0"
description = "A Simple password_strength_meter_app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.43.1",
]
